package exception;

public class Try_catch {

	public static void main(String[] args) {	
		int i = 10;
		for (int j =0; j<5; j++){
		i+= j;
		System.out.println("결과 : " + i);
		}
	}
}
